// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkXclRaUuST3pWjk65BSqYsZq32zLJRC4',
    appId: '1:28521925582:web:764b38007a6174566df99f',
    messagingSenderId: '28521925582',
    projectId: 'uts-061023',
    authDomain: 'uts-061023.firebaseapp.com',
    storageBucket: 'uts-061023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALFQHFo_SwfXWx5HnGaZAuIVDVUCbVQTI',
    appId: '1:28521925582:android:552c4723a7bdc0e56df99f',
    messagingSenderId: '28521925582',
    projectId: 'uts-061023',
    storageBucket: 'uts-061023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuckxlmQnAnMzPcrzyymGmDHeUcxroLNE',
    appId: '1:28521925582:ios:6c139dc7d07dc9ac6df99f',
    messagingSenderId: '28521925582',
    projectId: 'uts-061023',
    storageBucket: 'uts-061023.appspot.com',
    iosBundleId: 'com.example.manajemenbuku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuckxlmQnAnMzPcrzyymGmDHeUcxroLNE',
    appId: '1:28521925582:ios:90aefd1b6a5e73996df99f',
    messagingSenderId: '28521925582',
    projectId: 'uts-061023',
    storageBucket: 'uts-061023.appspot.com',
    iosBundleId: 'com.example.manajemenbuku.RunnerTests',
  );
}
